# Generated by Django 4.0.3 on 2022-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReposInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_repo', models.CharField(max_length=100, null=True)),
                ('about', models.CharField(max_length=100, null=True)),
                ('link_site', models.CharField(max_length=100, null=True)),
                ('stars', models.CharField(max_length=100, null=True)),
                ('forks', models.CharField(max_length=100, null=True)),
                ('watching', models.CharField(max_length=100, null=True)),
                ('commits', models.CharField(max_length=100, null=True)),
                ('commit_autor', models.CharField(max_length=100, null=True)),
                ('commit_name', models.CharField(max_length=100, null=True)),
                ('commit_date', models.CharField(max_length=100, null=True)),
                ('releases', models.CharField(max_length=100, null=True)),
                ('releases_version', models.CharField(max_length=100, null=True)),
                ('releases_date', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
