# Generated by Django 4.0.3 on 2022-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitparse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reposinfo',
            name='default_link',
            field=models.CharField(default='Some link', max_length=100),
        ),
    ]
